name: Build & Release
on:
  pull_request:
    branches:
      - master
      - main
  
  push:
    branches:
      - master
      - main

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.3.3"
      - run: flutter pub get
      - run: flutter build apk --release
      - name: Push to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.ACCESS_TOKEN }}
    